# Simple HPA using only CPU for testing
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: downloader-service-hpa
  namespace: microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: downloader-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  # Only CPU scaling for now
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      selectPolicy: Min