# HPA using only custom metrics from downloader-service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: downloader-service-hpa
  namespace: microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: downloader-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  # Scale based on download request rate
  - type: Pods
    pods:
      metric:
        name: downloader_download_requests_rate
      target:
        type: AverageValue
        averageValue: "3"  # Scale up when > 3 download req/sec per pod
  
  # Scale based on upload request rate  
  - type: Pods
    pods:
      metric:
        name: downloader_upload_requests_rate
      target:
        type: AverageValue
        averageValue: "2"  # Scale up when > 2 upload req/sec per pod
  
  # Scale based on active downloads
  - type: Pods
    pods:
      metric:
        name: downloader_active_downloads
      target:
        type: AverageValue
        averageValue: "2"  # Scale up when > 2 active downloads per pod
  
  # Scale based on active uploads
  - type: Pods
    pods:
      metric:
        name: downloader_active_uploads
      target:
        type: AverageValue
        averageValue: "2"  # Scale up when > 2 active uploads per pod
  
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30  # Faster scaling for file operations
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 180  # Conservative scale down
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      selectPolicy: Min