apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-metrics
  namespace: microservices
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  endpoints:
  - port: prometheus
    interval: 30s
    path: /metrics
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-metrics
  namespace: microservices
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - name: prometheus
    port: 15692
    targetPort: 15692
  type: ClusterIP 