apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: downloader-service-monitor
  namespace: microservices
  labels:
    app: downloader-service
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: downloader-service
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_name]
        targetLabel: pod
      - sourceLabels: [__meta_kubernetes_namespace]
        targetLabel: namespace