# Template file - DO NOT store actual secrets here
# Use this as a reference for creating secrets in ArgoCD
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: microservices
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
  MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: microservices
type: Opaque
stringData:
  MONGODB_USER: "${MONGODB_USER}"
  MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: microservices
type: Opaque
stringData:
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}" 