apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: pyroborn/user-service:53
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3003
        volumeMounts:
        - name: user-data
          mountPath: /app/data
        envFrom:
        - configMapRef:
            name: shared-env
        - configMapRef:
            name: user-service-config
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        - name: SERVICE_API_KEY
          valueFrom:
            secretKeyRef:
              name: service-api-keys
              key: SERVICE_API_KEY
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: user-data
        persistentVolumeClaim:
          claimName: user-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: microservices
spec:
  selector:
    app: user-service
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-user-data
  namespace: microservices
spec:
  template:
    spec:
      containers:
      - name: init-container
        image: busybox
        command: ['/bin/sh', '-c']
        args:
        - |
          if [ ! -f /data/users.json ]; then
            echo "Copying initial users data..."
            cp /secret/users.json /data/
            chmod 666 /data/users.json
            echo "Done."
          else
            echo "users.json already exists, skipping initialization."
          fi
        volumeMounts:
        - name: user-data
          mountPath: /data
        - name: initial-users
          mountPath: /secret
      volumes:
      - name: user-data
        persistentVolumeClaim:
          claimName: user-data-pvc
      - name: initial-users
        secret:
          secretName: initial-users-data
      restartPolicy: Never
  backoffLimit: 3
